version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install WGET
          command: 'apt-get update && apt-get install -y wget'
      - run:
          name: Install BUILD-ESSENTIALS
          command: 'apt-get update && apt-get install -y build-essential'
      - run:
          name: Install CMAKE 3.5
          command: |
            wget https://cmake.org/files/v3.5/cmake-3.5.2.tar.gz --no-check-certificate
            tar -zxvf cmake-3.5.2.tar.gz 
            cd cmake-3.5.2
            ./bootstrap --prefix=/usr
            make
            make install
      - run:
          name: Install GIT
          command: 'apt-get update && sudo apt-get install -y git'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Point Unit Testing
          command: './bin/tests' 