version: 2

jobs:
  build:
    docker:
      - image: "debian:bullseye"
    resources_class: small
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && apt-get install -y cmake'
      - run:
          name: Install GIT
          command: 'apt-get update && apt-get install -y git'
      - run:
          name: Install CATCH2
          command: |
            git clone https://github.com/catchorg/Catch2.git
            cd Catch2
            cmake -Bbuild -H. -DBUILD_TESTING=OFF
            cmake --build build/ --target install
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Point Unit Testing
          command: './bin/tests' 