version: 2.1

workflows:
  default:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: 
                - master
                - dev-nick
jobs:
  build-and-test:
    docker:
      - image: "debian:bullseye"
    resource_class: small
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Installing CMAKE
          command: 'apt-get update && apt-get install -y cmake'
      - run:
          name: Installing GIT
          command: 'apt-get update && sudo apt-get install -y git'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Point Unit Testing
          command: './bin/tests' 
